POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "6dfdbc90-fd34-4ed5-9292-b2ff3b32c52b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "b8e81e4c-4c5c-4b22-9075-c66c3652d6a0",
  "account_id_to": "0ffcaccd-ff68-45d3-80ed-2e54b32f4c5e",
  "amount": 110
}